import os
from dotenv import load_dotenv

load_dotenv()

MONGODB_URI = os.getenv("MONGODB_URI")
MONGODB_DB_NAME = os.getenv("MONGODB_DB_NAME")

HIGHLIGHTLY_API_KEY = os.getenv("HIGHLIGHTLY_API_KEY")
HIGHLIGHTLY_BASE_URL = os.getenv("HIGHLIGHTLY_BASE_URL")

FOOTBALLDATA_API_KEY = os.getenv("FOOTBALLDATA_API_KEY")
FOOTBALLDATA_BASE_URL = os.getenv("FOOTBALLDATA_BASE_URL")